name: Update Maoyan Data

on:
  schedule:
    # Runs every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
      TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install axios
      run: npm install axios --no-package-lock --no-save
      
    - name: Create data directory
      run: mkdir -p data
      
    - name: Run Maoyan data script
      run: node scripts/update-maoyan-data.js
      
    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add data/maoyan-data.json
        git diff --quiet && git diff --staged --quiet || git commit -m "Auto-update Maoyan data [skip ci]"
        git push
